name 'elkstack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elkstack'
long_description 'Installs/Configures elkstack'
version '0.1.0'
